apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Values.db.appName }}
  name: {{ .Values.db.appName }}
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Values.db.appName }}
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.db.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.appName }}
    spec:
      containers:
        - image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          name: {{ .Values.db.appName }}
          ports:
            - containerPort: {{ .Values.db.appPort }}
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.pgPass }}
            - name: POSTGRES_USER
              value: {{ .Values.db.pgUser }}
            - name: POSTGRES_DB
              value: {{ .Values.db.pgDB }}
          resources:
            {{- toYaml .Values.db.resources | nindent 12 }}
      terminationGracePeriodSeconds: 30
