---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.appName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: pgport
      port: {{ .Values.db.appPort }}
  selector:
    app: {{ .Values.db.appName }}
