apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: belas80/frontend
          imagePullPolicy: IfNotPresent
          name: frontend
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/static"
              name: my-vol
      volumes:
        - name: my-vol
          persistentVolumeClaim:
            claimName: my-volume-claim
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: prod
spec:
  ports:
    - name: web8000
      port: 8000
      targetPort: 80
      nodePort: 30080
  selector:
    app: frontend
  type: NodePort